### ISSUE TITLE
Default setting for initial capital letter with user names / passwords

### ISSUE THREAD

**Issue by rbschi** [ISN-Zurich/ISN-Learning-Cards#229]
Would be good not to have the first letter capitalize automatically (OK, this might be a setting with my iPhone, but it is still not very ideal)

**Comment by evangelia-mitsopoulou** [comment]
The problem is because the words Benutzername und Passwort are written with capital first letter in the language files. I changed it.

In english it  is ok :
i checked on my android device and it is written with small first letter in usernames and passwords
i checked on the simulator of iphone in Xcode and it is written with first letter of usernames and passwords small
