### ISSUE TITLE
horizontal ordering questions are not considered 

### ISSUE THREAD

**Issue by ISN-Zurich** [ISN-Zurich/ISN-Learning-Cards#98]
Current behavior: 
If a user adds a horizontal ordering questions into the question pool, the pool is considered as "invalid". 

Desired behavior: 
horizontal ordering questions should be treated as ordering questions, just like vertical ordering. Because IMS QTI does not distinguish between the different ordering types the Ilias types "horizontal" and "vertical" ordering should be treated in the same way.

**Comment by evangelia-mitsopoulou** [comment]
FIXED in folowing commits:

 5c6c039eb8484d881cdb1a2ab046cda7a1390e25 
24f860c7f31cbda921a7ec0607e9efe3260cc81b
aad627856e6deb75940ecf9d87f4b60055d0417f
83ae8d958e15226056b4a0eb9088ff7da232c542
1dadcafd2bd7c5bbbe703b0070df4cbc415341d8
77c7ef63a6c014bf66259fdfe0541329d56db1a2
5c6c039eb8484d881cdb1a2ab046cda7a1390e25
